steps:

# Step 1: Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/ci-cd-467305/ml-models/iris-model:latest',
      '.'
    ]

# Step 2: Push Docker Image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/ci-cd-467305/ml-models/iris-model:latest'
    ]

# Step 3: Run Docker Container to Train and Save Model Artifacts
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'run',
      '--rm',
      '-v',
      '/workspace/models:/app/models',
      'asia-south1-docker.pkg.dev/ci-cd-467305/ml-models/iris-model:latest',
      'python',
      'train.py'
    ]

# Step 4: Copy Trained Model to GCS Bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Uploading trained model to GCS..."
      gsutil cp -r /workspace/models gs://ml-cicd-bucket/models

# Step 5: Register Model with Vertex AI
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Registering model to Vertex AI..."
      gcloud ai models upload \
        --region=us-central1 \
        --display-name=iris-classifier \
        --container-image-uri=asia-south1-docker.pkg.dev/ci-cd-467305/ml-models/iris-model:latest \
        --artifact-uri=gs://ml-cicd-bucket/models 

options:
  substitutionOption: ALLOW_LOOSE

images:
  - 'asia-south1-docker.pkg.dev/ci-cd-467305/ml-models/iris-model:latest'

logsBucket: 'gs://ml-cicd-bucket/logs'