apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iris-model-service
spec:
  template:
    spec:
      containers:
        - image: iris-model-image
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"